//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIP.ChefsCorner.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecipe
    {
        public int rc_Id { get; set; }
        public byte[] rc_Image { get; set; }
        public string rc_Name { get; set; }
        public string rc_Description { get; set; }
        public string rc_Directions { get; set; }
        public int us_Id { get; set; }
        public string rc_Ingredients { get; set; }
    }
}
