//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIP.ChefsCorner.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecipeIngredient
    {
        public int ri_Id { get; set; }
        public int ri_Quantity { get; set; }
        public int ms_Id { get; set; }
        public string ri_Notes { get; set; }
        public int in_Id { get; set; }
        public int rc_Id { get; set; }
    }
}
