//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIP.ChefsCorner.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int us_Id { get; set; }
        public string us_ScreenName { get; set; }
        public string us_Email { get; set; }
        public string us_Pass { get; set; }
    }
}
